use FORM110
--PART A
select DOCUMENTO_IDENTIDAD, LUGAR, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DOMICILIO 
from DEPENDIENTE, LUGAR
where LUGAR.ID_LUGAR = DEPENDIENTE.ID_LUGAR AND DEPENDIENTE.DOCUMENTO_IDENTIDAD='6755488'
--PART B
select NUMERO_NIT, RAZON_SOCIAL, EMPLEADOR.DOMICILIO
from EMPLEADOR, DEPENDIENTE
where DEPENDIENTE.DOCUMENTO_IDENTIDAD='6755488' AND DEPENDIENTE.NUMERO_NIT_EMPLEADOR = EMPLEADOR.NUMERO_NIT
--PART C
select NRO_FACTURA, NIT, NUMERO_AUTORIZACION, FECHA, IMPORTE, CODIGO_CONTROL
from FACTURA, FORMULARIO_110, DEPENDIENTE
where FORMULARIO_110.NUMERO_ORDEN='1111' AND DEPENDIENTE.DOCUMENTO_IDENTIDAD='6755488' AND FACTURA.NUMERO_ORDEN_FORMULARIO = FORMULARIO_110.NUMERO_ORDEN AND FORMULARIO_110.DOCUMENTO_IDENTIDAD = DEPENDIENTE.DOCUMENTO_IDENTIDAD
-- PART D
select TOTAL_DETALLE, DETERMINACION_PAGO
from FORMULARIO_110, DEPENDIENTE
where DEPENDIENTE.DOCUMENTO_IDENTIDAD = '6755488' AND DEPENDIENTE.DOCUMENTO_IDENTIDAD = FORMULARIO_110.DOCUMENTO_IDENTIDAD

go